### ISSUE TITLE
What happened to "git-messenger.el"? I thought you were the author of that one?

### ISSUE THREAD

**Issue by ahungry** [syohex/emacs-git-messenger2#7]
What happened to "git-messenger.el"? I thought you were the author of that one?

Is this meant to supersede it?  I can't find reference to the old one on your github, but maybe it was never hosted there?

**Comment by syohex** [comment]
> Is this meant to supersede it?

No

I no longer maintain any emacs packages and I delegate all melpa packages to other people. I'm very tired from maintaining emacs packages.

I no longer use emacs(Use only IDE) This is my hobby product only for me.

You should use melpa version(https://github.com/emacsorphanage/git-messenger). If you have any issues or PR, please send them to there, not here.

**Comment by ahungry** [comment]
thanks for all your past contributions, they were very appreciated
